### ISSUE TITLE
대략적인 모델 연관관계

### ISSUE THREAD

**Issue by charlesuu** [Eat-Together6/EATOGETHER_2.0#37]
![image](https://user-images.githubusercontent.com/76809524/184089619-bc2f544c-5cf6-4632-9a10-af2c20c0486c.png)

**Comment by KimChanJin97** [comment]
![1](https://user-images.githubusercontent.com/102044895/184313863-f679dee7-d467-4ce9-a942-0570156fdeca.png)
모델 이걸로 수정했어요
